### ISSUE TITLE
Creating the Metadata file in the same folder of the binary file

### ISSUE THREAD

**Issue by agnoldo** [qawatake/obsidian-binary-file-manager-plugin#1]
Hello, first of all, thanks for the great work! I needed this plugin so much and it's helping me a lot.

Is it possible to create each Metadata note in the same folder of the respective binary file? If not, what do you think about it? One idea for solution: a new variable {{FOLDER}} could be created and it could be used in the "New file location" field on plugin options.

Cheers!

**Comment by agnoldo** [comment]
Hello, a quick update: using Templater and the following command I was able to solve the issue:

`	await tp.file.move("{{PATH}}".replace("{{NAME}}.{{EXTENSION}}", "{{NAME}}_{{EXTENSION}}.md"));
`

Thanks for your attention!

**Comment by qawatake** [comment]
@agnoldo 

Thank you for sharing a tip!

**Comment by owldown** [comment]
I was about to ask this same question. I wonder if this tip could be exposed more clearly in the documentation, rather than being hidden from new users as a closed issue. This use case and tip makes the plugin so much more valuable to me, so thanks to both of you!

**Comment by rapatel0** [comment]
How do you instantiate this? I tried the command but I get a templater error and blank binary file when I add it 

I expect that there might be a race condition with the rest of the fields.
