### ISSUE TITLE
Creating files for previously existing binaries

### ISSUE THREAD

**Issue by normanlamont** [qawatake/obsidian-binary-file-manager-plugin#3]
Apologies if this is the wrong place to be contacting you but I'm new to both Obsidian and Github so I wasn't sure of the protocol.  I installed this on my main vault, a Windows PC, yesterday, tested it with a new image file and it worked great.

This morning I found I couldn't open my iPad or iPhone Obsidian apps, or rather they took time - 8 minutes for the iPad. When I got into the iPhone one I discovered 2000+ new notes in my Inbox (where I'd set Binary File Manager to create new notes). The iPad wouldn't open at all.  When I then went to the main vault on the PC I find it still generating new notes.  I'm guessing it's generating a note for every image and PDF in my _resources folder. 

I'm just unsure what to do next.  If I delete these once they're created, will it just start creating them again?  I wonder how Obsidian Sync will affect it - will the iOS devices keep creating new notes and syncing them to the main vault? 

What I want is for Binary File Manager to operate only with new binaries, from the day I install ed it. That's what I assumed it would do. Perhaps I've made a mistake with one of the settings?

UPDATE: I deleted the newly made notes from my Inbox. (I couldn't do it in Obsidian because multiple file deletes don't work, but did it outside in Windows File Manager.) When I reopened Obsidian it quickly restarted creating 2000+ notes for all the binaries in my vault. I've now disabled the plugin until I get advice on continuing.

**Comment by qawatake** [comment]
@normanlamont 

The current version generates a note for every image and PDF. To ignore existing files, you have to generate notes for them once and remove the generated notes. So could you try the following on your PC?
1. Enable Binary File Manager.
2. Execute command `Binary File Manager: Create metadata for binary files` not `Binary File Manager: Create metadata for unlinked binary files`. You may need to run the command several times until no new files are generated.
3. Remove the generated notes that you don't want.

**Comment by normanlamont** [comment]
Thanks for replying. 
How do I execute the command in the way you say? I only have the 'Options' screen in Binary File Manager. Is there a command line somewhere? 
![binary file manager](https://user-images.githubusercontent.com/102355852/160234715-fe19726d-9fd3-43d1-b4ff-7eab40aecc1a.JPG)
I deleted all the files in File Explorer and set BFM auto detection to OFF but still every time I open Obsidian it creates new notes. This is creating a big issue for me in the synced versions on my phone and iPad as each time they are generated they get added there and as far as I can see there's no way to delete more than one note at a time on the apps.  (Not your problem, I know, I'll take it up with Obsidian).

**Comment by normanlamont** [comment]
Thanks for replying.  I did that but they keep filling up. I suspect it's not Binary File Manager that's generating them now, but they're being synced from my two mobile devices where they've all accumulated. I've shut down Binary File Manager until I can get an answer on the Obsidian forum on how to remove them from my mobile devices.

**Comment by normanlamont** [comment]
I've got rid of the files on the mobile devices, reinstated Binary File Manager and run it again. Everything seems to be under control and working fine. Thanks!
